#!/usr/bin/env bash

# dotfiles: Install or update dotfiles

PROGRAM_NAME="$(basename "$0")"

# Displays help text
print_help () {
    echo "$PROGRAM_NAME - Usage:"
    echo "    $PROGRAM_NAME --help                            Display this help message."
    echo "    $PROGRAM_NAME --tag <tag> --file <file>         Install dotfiles under <tag> in <file>."
}

if [[ $# -eq 0 ]]; then
    print_help
    exit 1
fi

# Parse given arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -f | --file)    file="$2"
                        shift
                        ;;
        -t | --tag)     tag="$2"
                        shift
                        ;;
        -h | --help)    print_help
                        exit 0
                        ;;
    esac
    shift
done

# Set colors
if tput colors &>/dev/null; then
    RED=$(tput setaf 1)
    YELLOW=$(tput setaf 3)
    RESET=$(tput sgr0)
else
    RED=''
    YELLOW=''
    RESET=''
fi

# Check given file exists
if [[ ! -f "$file" ]]; then
    echo "${RED}$PROGRAM_NAME: File not found: '$file'.${RESET}" >&2
    exit 1
fi

echo "Parsing '$file' for entries under '$tag'."

while read -r line || [[ -n "$line" ]]; do

    # For each line in the given file:
    # 1. Squeeze multiple spaces into one, then split into fields.
    # 2. If the tag matches the given tag, create the symbolic link.

    IFS=' ' read -r curr_tag target link <<< "$(tr -s ' ' <<< "$line")"

    if [[ "$curr_tag" == "$tag" ]]; then

        # Check target exists
        if [[ ! -f "$target" ]]; then
            echo "${RED}$PROGRAM_NAME: Target not found: '$target'.${RESET}" >&2
            exit 2
        fi

        echo "Creating symbolic link '$link' to '$target'."

        # Alert user that existing file will be overwritten
        if [[ -e "$link" ]]; then
            echo "${YELLOW}File '$link' already exists. Overwriting...${RESET}"
        fi

        # Create symbolic link directory if it does not exist
        if [[ ! -d "$(dirname "$link")" ]]; then
           mkdir -p "$(dirname "$link")" 
        fi

        # Forcibly create the symbolic link
        ln -sfn "$target" "$link"
    fi
done < "$file"

echo "All done."
