# tmux.conf

# - General -

# Set delay between prefix and command
set -s escape-time 1

# Set base index for windows and panes
set -g base-index 1
set -g pane-base-index 1


# - Key Mappings -

# Set prefix key
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# Reload configuration
bind r \
    source-file ~/.tmux.conf \; \
    display-message "Loading configuration..."

# Split panes
bind | split-window -h
bind _ split-window -v

# Move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Move between windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Copy and paste
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
unbind p
bind p paste-buffer

# Quick menu
bind e \
    display-menu -T "Quick Menu" \
        "New Window" n "new-window" \
        "Horizontal Split" _ "split-window" \
        "Vertical Split" | "split-window -h" \
        "Close Pane" x "kill-pane"
